name: sql_game
description: SQL Game Learning App with interactive animations, quizzes, and AI-powered features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  lottie: ^2.3.2
  http: ^1.1.0
  sqflite: ^2.2.8+4
  path: ^1.8.3
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.5
  path_provider: ^2.0.15
  url_launcher: ^6.2.5
  pdf: ^3.10.1
  flutter_quill: ^7.2.0
  flutter_dotenv: ^5.2.1
  share_plus: ^7.0.0
  flutter_markdown: ^0.7.6+2
  flutter_syntax_view: ^4.1.7
  google_fonts: ^6.2.1
  supabase_flutter: ^1.10.25
  google_sign_in: ^6.1.6
  flutter_appauth: ^6.0.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
    - assets/icons/google_icon.png
    - assets/icons/github_icon.png
    - .env 